# --- Change what appears in the banner --- #
title: Zareen's Language Website
description: This is my website for SML5202.

# --- Change language of site --- #
lang: en

# --- List of links in the navigation bar --- #
# --- Only change these if you change the name of your .md files!! --- #
# --- And, only change the names of the HTML files e.g. page2.html --- #
github:
  page1: index.html
  page2: grammar.html
  page3: page3.html
  page4: page4.html
  page5: page5.html
